name: Jekyll CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0 # Use your Ruby version
      - name: Install dependencies
        run: |
          gem install bundler
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: Clear Ruby Gems Cache
        run: rm -rf ~/.gem
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
